### ISSUE TITLE
[BUG] Appstream-helper does not correctly assign categories

### ISSUE THREAD

**Issue by Drsheppard01** [xplshn/pelf#68]
Engrampa is posted like a web browser

**Comment by Azathothas** [comment]
> Engrampa is posted like a web browser

It's not fault of @xplshn , The stuff at [pkgforge/pkgcache](https://github.com/pkgforge/pkgcache/) are written manually (for now), so it was a human error. Appstream-helper isn't used by [pkgforge/pkgcache](https://github.com/pkgforge/pkgcache/)
